-- SIGR v3.0 — segurança, perfis, auditoria e notificações
-- Execute UMA VEZ no SQL Editor do projeto Supabase antes de ativar Web Push.

begin;

-- Perfis de acesso. O primeiro usuário criado no projeto é preservado como ADMIN.
create table if not exists public.sigr_user_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'viewer' check (role in ('admin','operator','viewer')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.sigr_user_profiles (user_id, email, role)
select id, email, 'admin'
from auth.users
where not exists (select 1 from public.sigr_user_profiles where role = 'admin')
order by created_at asc
limit 1
on conflict (user_id) do update set role = 'admin', email = excluded.email, updated_at = now();

create or replace function public.sigr_create_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.sigr_user_profiles (user_id, email, role)
  values (new.id, new.email, 'viewer')
  on conflict (user_id) do update set email = excluded.email, updated_at = now();
  return new;
end;
$$;

drop trigger if exists sigr_auth_user_profile on auth.users;
create trigger sigr_auth_user_profile
after insert or update of email on auth.users
for each row execute function public.sigr_create_user_profile();

create or replace function public.sigr_current_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select coalesce((select role from public.sigr_user_profiles where user_id = auth.uid()), 'viewer');
$$;

create or replace function public.sigr_can_write()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select public.sigr_current_role() in ('admin','operator'); $$;

create or replace function public.sigr_is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$ select public.sigr_current_role() = 'admin'; $$;

-- Central de notificações persistente.
create table if not exists public.sigr_notifications (
  id bigint generated by default as identity primary key,
  category text not null default 'SIGR',
  title text not null,
  body text not null default '',
  target_user_id uuid references auth.users(id) on delete cascade,
  dedupe_key text unique,
  created_at timestamptz not null default now()
);

create index if not exists sigr_notifications_created_idx on public.sigr_notifications(created_at desc);

-- Assinaturas Web Push. O navegador nunca lê esta tabela diretamente.
create table if not exists public.sigr_push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null unique,
  subscription jsonb not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sigr_push_user_idx on public.sigr_push_subscriptions(user_id);

-- Horários padrão. Podem ser alterados depois sem mudar o código.
create table if not exists public.sigr_notification_settings (
  id boolean primary key default true check (id = true),
  consultation_day_before_after time not null default '18:00',
  consultation_today_after time not null default '06:00',
  daily_leader_after time not null default '20:00',
  consultation_enabled boolean not null default true,
  occurrence_milestone_enabled boolean not null default true,
  daily_leader_enabled boolean not null default true,
  updated_at timestamptz not null default now()
);
insert into public.sigr_notification_settings(id) values (true) on conflict (id) do nothing;

-- Auditoria imutável para ações feitas no banco.
create table if not exists public.sigr_audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid,
  actor_email text,
  action text not null,
  table_name text not null,
  record_id text,
  payload jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sigr_audit_created_idx on public.sigr_audit_log(created_at desc);

create or replace function public.sigr_write_audit()
returns trigger
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  row_json jsonb;
  old_json jsonb;
  new_json jsonb;
  uid uuid;
  mail text;
begin
  uid := auth.uid();
  select u.email into mail from auth.users u where u.id = uid;
  old_json := case when TG_OP in ('UPDATE','DELETE') then to_jsonb(old) else null end;
  new_json := case when TG_OP in ('INSERT','UPDATE') then to_jsonb(new) else null end;
  row_json := coalesce(new_json, old_json, '{}'::jsonb);
  insert into public.sigr_audit_log(actor_user_id, actor_email, action, table_name, record_id, payload)
  values (uid, mail, TG_OP, TG_TABLE_NAME, row_json->>'id', jsonb_build_object('old', old_json, 'new', new_json));
  if TG_OP = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

-- RLS: leitura para autenticados; gravação para ADMIN/OPERADOR; exclusão somente ADMIN.
alter table public.sigr_user_profiles enable row level security;
alter table public.sigr_notifications enable row level security;
alter table public.sigr_push_subscriptions enable row level security;
alter table public.sigr_notification_settings enable row level security;
alter table public.sigr_audit_log enable row level security;

drop policy if exists sigr_profiles_select on public.sigr_user_profiles;
drop policy if exists sigr_profiles_admin_update on public.sigr_user_profiles;
create policy sigr_profiles_select on public.sigr_user_profiles for select to authenticated using (user_id = auth.uid() or public.sigr_is_admin());
create policy sigr_profiles_admin_update on public.sigr_user_profiles for update to authenticated using (public.sigr_is_admin()) with check (public.sigr_is_admin());

drop policy if exists sigr_notifications_select on public.sigr_notifications;
create policy sigr_notifications_select on public.sigr_notifications for select to authenticated using (target_user_id is null or target_user_id = auth.uid());

drop policy if exists sigr_settings_select on public.sigr_notification_settings;
drop policy if exists sigr_settings_admin on public.sigr_notification_settings;
create policy sigr_settings_select on public.sigr_notification_settings for select to authenticated using (true);
create policy sigr_settings_admin on public.sigr_notification_settings for all to authenticated using (public.sigr_is_admin()) with check (public.sigr_is_admin());

drop policy if exists sigr_audit_admin_select on public.sigr_audit_log;
create policy sigr_audit_admin_select on public.sigr_audit_log for select to authenticated using (public.sigr_is_admin());

-- O serviço de push usa service_role. Nenhuma policy direta é criada para assinaturas ou escrita de notificações.

-- Políticas dos dados operacionais já existentes.
do $$
declare t text;
begin
  foreach t in array array['recruits','occurrences','events','medicalLeaves','sigr_config'] loop
    if to_regclass('public."' || t || '"') is not null then
      execute format('alter table public.%I enable row level security', t);
      execute format('drop policy if exists sigr_v3_select on public.%I', t);
      execute format('drop policy if exists sigr_v3_insert on public.%I', t);
      execute format('drop policy if exists sigr_v3_update on public.%I', t);
      execute format('drop policy if exists sigr_v3_delete on public.%I', t);
      execute format('create policy sigr_v3_select on public.%I for select to authenticated using (true)', t);
      execute format('create policy sigr_v3_insert on public.%I for insert to authenticated with check (public.sigr_can_write())', t);
      execute format('create policy sigr_v3_update on public.%I for update to authenticated using (public.sigr_can_write()) with check (public.sigr_can_write())', t);
      execute format('create policy sigr_v3_delete on public.%I for delete to authenticated using (public.sigr_is_admin())', t);
    end if;
  end loop;
end $$;

-- Garante que acesso anônimo não opere os dados do SIGR.
revoke all on table public.sigr_user_profiles, public.sigr_notifications, public.sigr_push_subscriptions, public.sigr_notification_settings, public.sigr_audit_log from anon;

-- Auditoria nas tabelas operacionais existentes.
do $$
declare t text;
begin
  foreach t in array array['recruits','occurrences','events','medicalLeaves','sigr_config'] loop
    if to_regclass('public."' || t || '"') is not null then
      execute format('drop trigger if exists sigr_v3_audit on public.%I', t);
      execute format('create trigger sigr_v3_audit after insert or update or delete on public.%I for each row execute function public.sigr_write_audit()', t);
    end if;
  end loop;
end $$;

commit;

-- Conferência rápida:
select role, count(*) from public.sigr_user_profiles group by role order by role;
