-- SIGR | Comunicação, identificação individual e chamadas
-- Execute uma única vez no Supabase: SQL Editor > New query > Run.

create extension if not exists pgcrypto;

create table if not exists public.sigr_operators (
  id uuid primary key default gen_random_uuid(),
  rank text not null check (char_length(rank) between 1 and 20),
  war_name text not null check (char_length(war_name) between 1 and 50),
  duty_function text not null default 'Operador' check (char_length(duty_function) <= 60),
  avatar_color text not null default '#2563eb',
  pin_salt text not null,
  pin_hash text not null,
  active boolean not null default true,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists sigr_operators_identity_unique
  on public.sigr_operators (lower(rank), lower(war_name))
  where active = true;

create table if not exists public.sigr_operator_sessions (
  token_hash text primary key,
  operator_id uuid not null references public.sigr_operators(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  expires_at timestamptz not null,
  user_agent text
);
create index if not exists sigr_operator_sessions_operator_idx on public.sigr_operator_sessions(operator_id, expires_at desc);

create table if not exists public.sigr_operator_attempts (
  id bigint generated by default as identity primary key,
  operator_id uuid references public.sigr_operators(id) on delete cascade,
  auth_user_id uuid references auth.users(id) on delete cascade,
  success boolean not null default false,
  attempted_at timestamptz not null default now()
);
create index if not exists sigr_operator_attempts_recent_idx on public.sigr_operator_attempts(operator_id, attempted_at desc);

create table if not exists public.sigr_operator_activity (
  id bigint generated by default as identity primary key,
  operator_id uuid not null references public.sigr_operators(id) on delete restrict,
  action text not null check (char_length(action) between 1 and 80),
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sigr_operator_activity_recent_idx on public.sigr_operator_activity(operator_id, created_at desc);

create table if not exists public.sigr_chat_messages (
  id bigint generated by default as identity primary key,
  channel_type text not null check (channel_type in ('group','private')),
  sender_operator_id uuid not null references public.sigr_operators(id) on delete restrict,
  recipient_operator_id uuid references public.sigr_operators(id) on delete restrict,
  body text,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  constraint sigr_chat_private_recipient check (
    (channel_type = 'group' and recipient_operator_id is null)
    or (channel_type = 'private' and recipient_operator_id is not null and recipient_operator_id <> sender_operator_id)
  ),
  constraint sigr_chat_body_length check (body is null or char_length(body) between 1 and 2000)
);
create index if not exists sigr_chat_group_idx on public.sigr_chat_messages(channel_type, created_at desc);
create index if not exists sigr_chat_sender_idx on public.sigr_chat_messages(sender_operator_id, created_at desc);
create index if not exists sigr_chat_recipient_idx on public.sigr_chat_messages(recipient_operator_id, created_at desc);

create table if not exists public.sigr_message_reads (
  reader_operator_id uuid not null references public.sigr_operators(id) on delete cascade,
  conversation_key text not null,
  last_read_at timestamptz not null default now(),
  primary key (reader_operator_id, conversation_key)
);

create table if not exists public.sigr_comm_push_subscriptions (
  endpoint text primary key,
  operator_id uuid not null references public.sigr_operators(id) on delete cascade,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists sigr_comm_push_operator_idx on public.sigr_comm_push_subscriptions(operator_id);

create table if not exists public.sigr_calls (
  id uuid primary key default gen_random_uuid(),
  caller_operator_id uuid not null references public.sigr_operators(id) on delete restrict,
  recipient_operator_id uuid not null references public.sigr_operators(id) on delete restrict,
  status text not null default 'ringing' check (status in ('ringing','accepted','rejected','ended','missed')),
  created_at timestamptz not null default now(),
  answered_at timestamptz,
  ended_at timestamptz,
  constraint sigr_calls_distinct_people check (caller_operator_id <> recipient_operator_id)
);
create index if not exists sigr_calls_recipient_status_idx on public.sigr_calls(recipient_operator_id, status, created_at desc);

create table if not exists public.sigr_call_signals (
  id bigint generated by default as identity primary key,
  call_id uuid not null references public.sigr_calls(id) on delete cascade,
  sender_operator_id uuid not null references public.sigr_operators(id) on delete cascade,
  recipient_operator_id uuid not null references public.sigr_operators(id) on delete cascade,
  kind text not null check (kind in ('offer','answer','ice','hangup')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists sigr_call_signals_call_idx on public.sigr_call_signals(call_id, id);

-- O navegador não acessa diretamente PINs, privados ou sinais de chamada.
-- Toda operação passa pela Edge Function, que valida a sessão principal e o token individual.
alter table public.sigr_operators enable row level security;
alter table public.sigr_operator_sessions enable row level security;
alter table public.sigr_operator_attempts enable row level security;
alter table public.sigr_operator_activity enable row level security;
alter table public.sigr_chat_messages enable row level security;
alter table public.sigr_message_reads enable row level security;
alter table public.sigr_comm_push_subscriptions enable row level security;
alter table public.sigr_calls enable row level security;
alter table public.sigr_call_signals enable row level security;

revoke all on table public.sigr_operators from anon, authenticated;
revoke all on table public.sigr_operator_sessions from anon, authenticated;
revoke all on table public.sigr_operator_attempts from anon, authenticated;
revoke all on table public.sigr_operator_activity from anon, authenticated;
revoke all on table public.sigr_chat_messages from anon, authenticated;
revoke all on table public.sigr_message_reads from anon, authenticated;
revoke all on table public.sigr_comm_push_subscriptions from anon, authenticated;
revoke all on table public.sigr_calls from anon, authenticated;
revoke all on table public.sigr_call_signals from anon, authenticated;

-- Limpeza automática recomendada para ser usada pelo cron já existente.
create or replace function public.sigr_cleanup_communications()
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  delete from public.sigr_operator_sessions where expires_at < now();
  delete from public.sigr_operator_attempts where attempted_at < now() - interval '30 days';
  delete from public.sigr_call_signals where created_at < now() - interval '1 day';
  update public.sigr_calls set status = 'missed', ended_at = now()
    where status = 'ringing' and created_at < now() - interval '5 minutes';
end;
$$;
revoke all on function public.sigr_cleanup_communications() from public, anon, authenticated;
